common/models/TagNews.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "tag_news".
 *
 * @property integer $tag_id
 * @property integer $news_id
 */
class TagNews extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tag_news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tag_id', 'news_id'], 'required'],
            [['tag_id', 'news_id'], 'integer'],
        ];
    }
    public function getDetail()
    {
        return $this->hasOne(Tags::className(), ['tag_id' => 'tag_id']);
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'tag_id' => 'Tag ID',
            'news_id' => 'News ID',
        ];
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\User;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            $this->goMainPage();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $this->goMainPage();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function goMainPage(){
        if(Yii::$app->user->identity->role_id == User::role_superadmin)
            return $this->redirect(['news/index']);

        if(Yii::$app->user->identity->role_id == User::role_acceptor)
            return $this->redirect(['news/index']);

        if(Yii::$app->user->identity->role_id == User::role_publisher)
            return $this->redirect(['news/index']);

        if(Yii::$app->user->identity->role_id == User::role_editor)
            return $this->redirect(['news/index']);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRegister()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new RegisterForm();

        if ($model->load(Yii::$app->request->post())) {
         //$model->save();
          $model->register();
           //print_r($model);die;
           return $this->redirect(['login']);
        }
        return $this->render('register', [
            'model' => $model,
        ]);

    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\db\Query;
use yii\helpers\Url;
use yii\data\Pagination;

use common\models\Menu;
use common\models\News;
use common\models\Config;
use common\models\HotNews;
use common\models\Advertise;
use common\helpers\Helper;
/**
 * Site controller
 */
class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index','bai-viet','danh-muc', 'tim-kiem', 'error'],
                        'allow' => true,
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                ],
            ],
        ];
    }
    /**
     * @inheritdoc
     */
    public function actions()
    {
        /*$allowed_hosts = array('demo.doanhnghiep.net.vn');
        if (!isset($_SERVER['HTTP_HOST']) || !in_array($_SERVER['HTTP_HOST'], $allowed_hosts)) {
            header($_SERVER['SERVER_PROTOCOL'].' 400 Bad Request');
            exit;
        }*/
        $this->view->params['menu'] = Menu::getMenu();
        if(isset($_GET['mobile']) &&  $_GET['mobile'] == true){
            $this->view->params['desktop'] =  1;
        }else{
            $this->view->params['desktop'] =  0;
        }
        $this->view->params['ads'] = Advertise::getAds();
        $this->view->params['config'] = Config::find()->one();
        $hn = HotNews::find()->one();
        $this->view->params['newest'] = News::find()
                                        ->where(["news_status" => News::status_published])
                                        ->andWhere(['not in','news_id',explode(",", $hn->special_news)])
                                        ->orderBy('news.published_at DESC')
                                        ->limit(6)->all();
        $this->view->params['top'] = News::find()
                                    ->where(['>=','created_at' , time() - 15*86400])
                                    ->andWhere(["news_status" => News::status_published])
                                    ->orderBy('news_viewed DESC')
                                    ->limit(15)->all();
        $this->enableCsrfValidation = false;
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    
    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex($slug='')
    {
        $hn = HotNews::find()->one();
        return $this->render('index',[
            'page' => Menu::getMenuWithNews(3),
            'hot' => News::find()
                    ->where(['news_id' => $hn->hotest])
                    ->andWhere(["news_status" => News::status_published])->one(),
            'highlight' => News::find()
                    ->where('news_id IN ('.$hn->others.')')
                    ->andWhere(["news_status" => News::status_published])->all(),
            'new' => News::find()
                    ->where('news_id IN ('.$hn->special_news.')')
                    ->andWhere(["news_status" => News::status_published])->one()
        ]);
    }
    
    public function actionBaiViet($slug){
        $post = News::find()->where(['news_slug' => $slug])
                ->andWhere(["news_status" => News::status_published])->one();
        if(!$post) {
            return $this->redirect('/',302);
        }
        $post->news_viewed = $post->news_viewed + 1;
        $post->save();
        if($post->other_news)
            $post->other = News::find()->where(['news_id' => explode(',',$post->other_news)])->all();
        $post->news_viewed = $post->news_viewed + 1;
        $post->save();
        return $this->render('post',[
            'post' => $post,
            'sidemenu' => Menu::getSuggestMenu($post->menu_id),
            'recomend' => News::find()
                            ->leftJoin('cate_news', 'cate_news.news_id = news.news_id')
                            ->where(["news_status" => News::status_published])
                            ->andWhere(['cate_news.cate_id' => Helper::cateToArray($post->cateNews) ])
                            ->orderBy('news.published_at DESC')
                            ->limit(8)
                            ->all()
        ]);
    }
    public function actionTimKiem($keyword){
        $query = News::find()
                        ->where(["news_status" => News::status_published])
                        ->andWhere(['like', 'news_title', '%'.addslashes($keyword). '%', false])
                        ->orderBy('news_id DESC');
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        return $this->render('category', [
             'models' => $models,
             'sidemenu' => Menu::getSuggestMenu(2),
             'pages' => $pages,
             'title_cate' => 'Kết quả tìm kiếm: '.$keyword
        ]);
    }
    public function actionDanhMuc($slug)
    {
        $menu = Menu::find()->where(['menu_link' => $slug])->one();
        $menu->categories =  $menu->getCateMenu()->all();
        $list_cate = [];
        foreach($menu->categories as $cate){
            $list_cate[] = $cate->cate_id;
        }
        $query = News::find()->joinWith('cateNews')
                        ->where(["news_status" => News::status_published])
                        ->andWhere(['cate_news.cate_id' => $list_cate ])
                        ->orderBy('news.news_id DESC');
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('category', [
             'models' => $models,
             'sidemenu' => Menu::getSuggestMenu($menu->menu_id),
             'pages' => $pages,
             'title_cate' => 'Danh mục: '.$menu->menu_title
        ]);
    }
}

frontend/views/site/category.php
<?php
    use common\helpers\Helper;
    use yii\helpers\Url;
    use yii\widgets\LinkPager;
    $this->title = $title_cate;
?>
    <?php $this->beginBlock('meta_block'); ?>
        <meta name="title" content="<?= $this->params['config']->title ?>" />
        <meta name="description" content="<?= $this->params['config']->desciprtion ?>" />
        <meta name="keywords" content="<?= $this->params['config']->keyword ?>" />
        <meta property="og:title" content="<?= $this->params['config']->title_social ?>" />
        <meta property="og:description" content="<?= $this->params['config']->description_social ?>" />
        <?php $this->endBlock(); ?>
            <section class="row">
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-sm-9">
                            <div class="content main">
                                <div class="info clearfix">
                                    <div class="pull-left">
                                        <h1 class="cate"><?= $title_cate ?></h1>
                                    </div>
                                </div>
                                <br>
                            </div>
                            <?php if(count($models) > 0 ): ?>
                                <article class="post post-main">
                                    <div class="thumbnail">
                                        <a href="<?= Helper::getPostUrl($models[0]->news_slug) ?>" class="img-thumb">
                                            <div class="r43">
                                                <div class="r43-img">
                                                    <img src="<?= Helper::getPostImg($models[0]) ?>" alt="<?= $models[0]->news_title ?>">
                                                </div>
                                            </div>
                                        </a>
                                        <div class="caption">
                                            <a href="<?= Helper::getPostUrl($models[0]->news_slug) ?>">
                                                <h2><?= $models[0]->news_title ?></h2>
                                            </a>
                                            <p>
                                                <?= $models[0]->news_description ?>
                                            </p>
                                        </div>
                                    </div>
                                </article>
                                <div class="article">
                                    <?php foreach($models as $key => $post):?>
                                        <?php if($key > 0):?>
                                            <article class="post post-wide">
                                                <div class="thumbnail">
                                                    <div class="row">
                                                        <div class="col-xs-4">
                                                            <a href="<?= Helper::getPostUrl($post->news_slug) ?>">
                                                                <div class="r43">
                                                                    <div class="r43-img">
                                                                        <img src="<?= Helper::getPostImg($post) ?>" alt="<?=$post->news_title ?>">
                                                                    </div>
                                                                </div>
                                                            </a>
                                                        </div>
                                                        <div class="col-xs-8">
                                                            <div class="caption">
                                                                <a href="<?= Helper::getPostUrl($post->news_slug) ?>" class="short_link regular"><?=$post->news_title ?></a>
                                                                <p>
                                                                    <?= $post->news_description  ?>
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </article>
                                            <?php endif; ?>
                                                <?php endforeach;?>
                                </div>
                                <?php echo LinkPager::widget([
                        'pagination' => $pages,
                    ]); ?>
                                    <?php else:?>
                                        <h3>Không tìm thấy kết quả nào</h3>
                                        <?php endif;?>
                        </div>
                        <div class="col-sm-3">
                            <ul class="list-group no-style sidebar">
                                <?php foreach($this->params['newest'] as $key => $post):?>
                                    <li class="list-group-item">
                                        <?php if($key == 0): ?>
                                            <div class="r43">
                                                <div class="r43-img">
                                                    <img src="<?= Helper::getPostImg($post) ?>" alt="<?= $post->news_title ?>">
                                                </div>
                                            </div>
                                            <?php endif; ?>
                                                <a href="<?= Helper::getPostUrl($post->news_slug) ?>" class="short_link"><?=$post->news_title ?></a>
                                    </li>
                                    <?php endforeach;?>
                            </ul>
                            <?php foreach($sidemenu as $key => $menu):?>
                                <div class="top-post">
                                    <div class="title-block">
                                        <a href="<?= Helper::getCategoryUrl($menu->menu_link) ?>"><h2><?= $menu->menu_title ?></h2></a>
                                    </div>
                                    <ul class="list-group no-style">
                                        <?php foreach($menu->posts as $key => $post):?>
                                            <li class="list-group-item">
                                                <a href="<?= Helper::getPostUrl($post->news_slug) ?>" class="short_link"><?=$post->news_title ?></a>
                                            </li>
                                            <?php endforeach;?>
                                    </ul>
                                </div>
                                <?php endforeach;?>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 hidden-xs">
                    <div class="ads block-ads">
                        <a rel="nofollow" href="<?= $this->params['ads']->top_post->link ?>">
                        <img src="<?= $this->params['ads']->top_post->image ?>" class="hide-ads" alt="">
                        </a>
                    </div>
                    <div class="ads block-ads">
                        <a rel="nofollow" href="<?= $this->params['ads']->post_1->link ?>">
                        <img src="<?= $this->params['ads']->post_1->image ?>" class="hide-ads" alt="">
                        </a>
                    </div>
                    <div class="top-post suggest-block">
                        <div class="title-block">
                            <h2>BÀI ĐỌC NHIỀU NHẤT</h2>
                        </div>
                        <ul class="list-group no-style">
                            <?php foreach($this->params['top'] as $key => $post):?>
                                <li class="list-group-item">
                                    <a href="<?= Helper::getPostUrl($post->news_slug) ?>" class="short_link"><?=$post->news_title ?></a>
                                </li>
                                <?php endforeach;?>
                        </ul>
                    </div>
                    <div class="ads block-ads">
                        <a rel="nofollow" href="<?= $this->params['ads']->post_2->link ?>">
                        <img src="<?= $this->params['ads']->post_2->image ?>" class="hide-ads" alt="">
                        </a>
                    </div>

                    <div class="ads block-ads">
                        <a rel="nofollow" href="<?= $this->params['ads']->post_3->link ?>">
                        <img src="<?= $this->params['ads']->post_3->image ?>" class="hide-ads" alt="">
                        </a>
                    </div>
                    <div class="ads block-ads">
                        <a rel="nofollow" href="<?= $this->params['ads']->slidebar_1->link ?>">
                        <img src="<?= $this->params['ads']->slidebar_1->image ?>" class="hide-ads" alt="">
                        </a>
                    </div>
                    <div class="ads block-ads">
                        <a rel="nofollow" href="<?= $this->params['ads']->slidebar_2->link ?>">
                        <img src="<?= $this->params['ads']->slidebar_2->image ?>" class="hide-ads" alt="">
                        </a>
                    </div>
                </div>
            </section>

frontend/views/site/error.php
<p>Lỗi</p>

frontend/views/site/post.php
<?php

$this->title = $post->news_title;
use common\helpers\Helper;
use yii\helpers\Url;

?>
    <?php $this->beginBlock('meta_block'); ?>
        <meta name="title" content="<?= $post->news_title ?>" />
        <meta name="description" content="<?= $post->news_description ?>" />
        <meta name="keywords" content="Dieu Anh Biet, Chi Dan, , , lyrics, loi bai hat, chat luong cao" />
        <meta property="og:title" content="<?= $post->news_title ?> | Bài viết" />
        <meta property="og:description" content="<?= $post->news_description ?>" />
        <meta property="og:image" content="<?= Helper::getPostImg($post) ?>" />
        <meta property="og:url" content="<?= Helper::getPostUrl($post->news_slug,true) ?>" />
        <meta property="og:type" content="article" />
        <?php $this->endBlock(); ?>
            <section class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-sm-9">
                            <article class="content main">
                                <div class="info clearfix">
                                    <div class="pull-left">
                                        <span class="date">Xuất bản ngày: <?= date('d/m/Y h:i a',$post->published_at) ?></span>
                                    </div>
                                    <div class="pull-right">
                                        <div class="fb-like" data-href="<?= Helper::getPostUrl($post->news_slug,true) ?>" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>
                                    </div>
                                </div>
                                <h1><?= $post->news_title ?></h1>
                                <div class="fck_detail width_common block_ads_connect">
                                    <div class="post-description">
                                        <strong><?= str_replace("(Doanhnghiep.net.vn)","<span class='sitename'>Doanhnghiep.net.vn</span>",$post->news_description);  ?></strong>
                                    </div>
                                    <?php if($post->other): ?>
                                        <div class="other-news">
                                            <ul class="list-group">
                                                <?php  foreach($post->other as $key => $pos):?>
                                                    <li class="list-group-item">
                                                        <a href="<?= Helper::getPostUrl($pos->news_slug) ?>" class="short_link"><?=$pos->news_title ?></a>
                                                    </li>
                                                    <?php endforeach;?>
                                            </ul>
                                        </div>
                                        <?php  endif; ?>
                                            <div class="post--main">
                                                <?= $post->news_content ?>
                                            </div>
                                            <div class="post--author text-right">
                                                <strong><?= $post->author ?> <?= $post->source ? '('.$post->source.')' :'' ?> </strong>
                                            </div>
                                </div>
                            </article>
                            <div class="tag">
                                <br>
                                <br>
                                <h4>Từ khoá bài viết</h4>
                                <?php if(!count($post->tags)): ?>
                                    <span>Bài viết không được gắn tag nào</span>
                                    <?php endif; ?>
                                        <?php  foreach($post->tags as $key => $tag):?>
                                            <span class="tag"><?= $tag->detail->tag_title ?></span>
                                            <?php endforeach;?>
                            </div>
                        </div>
                        <div class="col-sm-3 hide-ads">
                            <ul class="list-group no-style sidebar">
                                <?php foreach($this->params['newest'] as $key => $pos):?>
                                    <li class="list-group-item">
                                        <?php if($key == 0): ?>
                                            <div class="r43">
                                                <div class="r43-img">
                                                    <img src="<?= Helper::getPostImg($pos) ?>" alt="<?= $pos->news_title ?>">
                                                </div>
                                            </div>
                                            <?php endif; ?>
                                                <a href="<?= Helper::getPostUrl($pos->news_slug) ?>" class="short_link"><?=$pos->news_title ?></a>
                                    </li>
                                    <?php endforeach;?>
                            </ul>
                            <?php foreach($sidemenu as $key => $menu):?>
                                <div class="top-post">
                                    <div class="title-block">
                                        <a href="<?= Helper::getCategoryUrl($menu->menu_link) ?>"><h2><?= $menu->menu_title ?></h2></a>
                                    </div>
                                    <ul class="list-group no-style">
                                        <?php foreach($menu->posts as $key => $post):?>
                                            <li class="list-group-item">
                                                <a href="<?= Helper::getPostUrl($post->news_slug) ?>" class="short_link"><?=$post->news_title ?></a>
                                            </li>
                                            <?php endforeach;?>
                                    </ul>
                                </div>
                                <?php endforeach;?>
                        </div>
                    </div>
                    <div class="extra">
                        <div class="comments">
                            <div class="top">
                                Ý kiến bạn đọc
                            </div>
                            <div class="content">
                                <div class="fb-comments" data-order-by="social" data-width="100%" data-href="<?= Helper::getPostUrl($post->news_slug,true) ?>" data-numposts="15"></div>
                            </div>
                        </div>

                        <div class="category">
                            <ul class="nav nav-tabs category-tabs">
                                <li class="active"><a href="#" class="short_link">TIN CÙNG CHUYÊN MỤC</a></li>
                            </ul>
                            <div class="article">
                                <div class="row">
                                    <?php foreach($recomend as $key => $pos):?>
                                        <div class="col-xs-6 col-sm-3">
                                            <article class="post post-small">
                                                <div class="thumbnail">
                                                    <a href="<?= Helper::getPostUrl($pos->news_slug) ?>">
                                                        <div class="r43">
                                                            <div class="r43-img">
                                                                <img src="<?= Helper::getPostImg($pos) ?>" alt="<?=$pos->news_title ?>">
                                                            </div>
                                                        </div>
                                                    </a>
                                                    <div class="caption">
                                                        <a href="<?= Helper::getPostUrl($pos->news_slug) ?>" class="short_link"><h4><?=$pos->news_title ?></h4></a>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                        <?php endforeach;?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 hide-ads">
                    <div class="ads block-ads">
                        <a rel="nofollow" href="<?= $this->params['ads']->top_post->link ?>">
                        <img src="<?= $this->params['ads']->top_post->image ?>" class="hide-ads" alt="">
                        </a>
                    </div>
                    <div class="ads block-ads">
                        <a rel="nofollow" href="<?= $this->params['ads']->post_1->link ?>">
                        <img src="<?= $this->params['ads']->post_1->image ?>" class="hide-ads" alt="">
                        </a>
                    </div>
                    <div class="top-post suggest-block">
                        <div class="title-block">
                            <h2>BÀI ĐỌC NHIỀU NHẤT</h2>
                        </div>
                        <ul class="list-group no-style">
                            <?php foreach($this->params['top'] as $key => $pos):?>
                                <li class="list-group-item">
                                    <a href="<?= Helper::getPostUrl($pos->news_slug) ?>" class="short_link"><?=$pos->news_title ?></a>
                                </li>
                                <?php endforeach;?>
                        </ul>
                    </div>
                    <div class="ads block-ads">
                       <a rel="nofollow" href="<?= $this->params['ads']->post_2->link ?>">
                        <img src="<?= $this->params['ads']->post_2->image ?>" class="hide-ads" alt="">
                        </a>
                    </div>
                    <div class="ads block-ads">
                       <a rel="nofollow" href="<?= $this->params['ads']->post_3->link ?>">
                        <img src="<?= $this->params['ads']->post_3->image ?>" class="hide-ads" alt="">
                        </a>
                    </div>
                </div>
            </section>